import { TStudy } from "../types/study";

export const studyDatas: TStudy[] = [
  {
    id: "1",
    creatorId: "1",
    atmosphere: ["serious", "friendly", "professional"],
    category: "개발 · 테크",
    src: "/img/studyItem/studyItemImg1.png",
    type: "온라인",
    dayOfWeek: "매주 월",
    startTime: "18:00",
    endTime: "20:00",
    title: "C언어 기초부터 함께 배울 스터디 모집",
    startDate: "07.01",
    endDate: "07.30",
    location: "zoom",
    maxParticipants: 4,
    rate: 4.5,
    currentParticipants: [
      {
        userId: "1",
        userName: "웅진",
        role: "팀장",
        profileImage: "/img/profile/example1.png",
      },
      {
        userId: "2",
        userName: "체리콜라",
        role: "기록팀장",
        profileImage: "/img/profile/example2.png",
      },
      {
        userId: "3",
        userName: "취뽀하자",
        role: "일정팀장",
        profileImage: "/img/profile/example3.png",
      },
    ],
    desiredMember: {
      ageRange: "20대",
      studyLevel: "비기너",
      roles: ["과제팀장", "알림팀장", "환경팀장"],
    },
  },
  {
    id: "2",
    creatorId: "2",
    atmosphere: ["serious", "friendly", "professional"],
    category: "디자인",
    src: "/img/studyItem/studyItemImg2.png",
    type: "오프라인",
    dayOfWeek: "매주 화",
    startTime: "19:00",
    endTime: "21:00",
    title: "블렌더 테크닉 향상 및 피드백 스터디",
    startDate: "09.01",
    endDate: "12.01",
    rate: 3.8,
    location: "성동구",
    maxParticipants: 4,
    currentParticipants: [],
    desiredMember: {
      ageRange: "20대",
      studyLevel: "비기너",
      roles: ["과제팀장", "알림팀장", "환경팀장"],
    },
  },
  {
    id: "3",
    creatorId: "3",
    atmosphere: ["serious", "friendly", "professional"],
    rate: 3.8,
    category: "마케팅",
    src: "/img/studyItem/studyItemImg3.png",
    type: "온라인",
    dayOfWeek: "매주 수",
    startTime: "17:00",
    endTime: "19:00",
    title: "기획안 작성 노하우 강의 들을 취준생 구해요!",
    startDate: "07.15",
    endDate: "10.15",
    location: "zoom",
    maxParticipants: 6,
    currentParticipants: [],
    desiredMember: {
      ageRange: "20대",
      studyLevel: "비기너",
      roles: ["과제팀장", "알림팀장", "환경팀장"],
    },
  },
  {
    id: "4",
    creatorId: "4",
    atmosphere: ["serious", "friendly", "professional"],
    rate: 3.8,
    category: "경제",
    src: "/img/studyItem/studyItemImg4.png",
    type: "오프라인",
    dayOfWeek: "매주 목",
    startTime: "10:00",
    endTime: "12:00",
    title: "주식 투자 재테크 강의 들을 주린이들 모임",
    startDate: "10.10",
    endDate: "11.01",
    location: "서초구",
    maxParticipants: 6,
    currentParticipants: [],
    desiredMember: {
      ageRange: "20대",
      studyLevel: "비기너",
      roles: ["과제팀장", "알림팀장", "환경팀장"],
    },
  },
  {
    id: "5",
    creatorId: "5",
    atmosphere: ["serious", "friendly", "professional"],
    rate: 3.8,
    category: "외국어",
    src: "/img/studyItem/studyItemImg5.png",
    type: "온라인",
    dayOfWeek: "매주 월",
    startTime: "18:30",
    endTime: "20:30",
    title: "AI Study Group",
    startDate: "06.01",
    endDate: "12.01",
    location: "zoom",
    maxParticipants: 4,
    currentParticipants: [],
    desiredMember: {
      ageRange: "20대",
      studyLevel: "비기너",
      roles: ["과제팀장", "알림팀장", "환경팀장"],
    },
  },
  {
    id: "6",
    creatorId: "6",
    atmosphere: ["serious", "friendly", "professional"],
    rate: 3.8,
    category: "외국어",
    src: "/img/studyItem/studyItemImg5.png",
    type: "온라인",
    dayOfWeek: "매주 월",
    startTime: "18:30",
    endTime: "20:30",
    title: "AI Study Group",
    startDate: "06.01",
    endDate: "12.01",
    location: "zoom",
    maxParticipants: 4,
    currentParticipants: [],
    desiredMember: {
      ageRange: "20대",
      studyLevel: "비기너",
      roles: ["과제팀장", "알림팀장", "환경팀장"],
    },
  },
  {
    id: "7",
    creatorId: "7",
    atmosphere: ["serious", "friendly", "professional"],
    rate: 3.8,
    category: "외국어",
    src: "/img/studyItem/studyItemImg5.png",
    type: "온라인",
    dayOfWeek: "매주 월",
    startTime: "18:30",
    endTime: "20:30",
    title: "AI Study Group",
    startDate: "06.01",
    endDate: "12.01",
    location: "zoom",
    maxParticipants: 4,
    currentParticipants: [],
    desiredMember: {
      ageRange: "20대",
      studyLevel: "비기너",
      roles: ["과제팀장", "알림팀장", "환경팀장"],
    },
  },
  {
    id: "8",
    creatorId: "8",
    atmosphere: ["serious", "friendly", "professional"],
    rate: 3.8,
    category: "외국어",
    src: "/img/studyItem/studyItemImg5.png",
    type: "온라인",
    dayOfWeek: "매주 월",
    startTime: "18:30",
    endTime: "20:30",
    title: "AI Study Group",
    startDate: "06.01",
    endDate: "12.01",
    location: "zoom",
    maxParticipants: 4,
    currentParticipants: [],
    desiredMember: {
      ageRange: "20대",
      studyLevel: "비기너",
      roles: ["과제팀장", "알림팀장", "환경팀장"],
    },
  },
  {
    id: "9",
    creatorId: "9",
    atmosphere: ["serious", "friendly", "professional"],
    rate: 3.8,
    category: "외국어",
    src: "/img/studyItem/studyItemImg5.png",
    type: "온라인",
    dayOfWeek: "매주 월",
    startTime: "18:30",
    endTime: "20:30",
    title: "AI Study Group",
    startDate: "06.01",
    endDate: "12.01",
    location: "zoom",
    maxParticipants: 4,
    currentParticipants: [],
    desiredMember: {
      ageRange: "20대",
      studyLevel: "비기너",
      roles: ["과제팀장", "알림팀장", "환경팀장"],
    },
  },
  {
    id: "10",
    creatorId: "10",
    atmosphere: ["serious", "friendly", "professional"],
    rate: 3.8,
    category: "외국어",
    src: "/img/studyItem/studyItemImg5.png",
    type: "온라인",
    dayOfWeek: "매주 월",
    startTime: "18:30",
    endTime: "20:30",
    title: "AI Study Group",
    startDate: "06.01",
    endDate: "12.01",
    location: "zoom",
    maxParticipants: 4,
    currentParticipants: [],
    desiredMember: {
      ageRange: "20대",
      studyLevel: "비기너",
      roles: ["과제팀장", "알림팀장", "환경팀장"],
    },
  },
];
